name: alpine-matrix-action
description: GitHub Action to generate Alpine releases matrix

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  count:
    description: 'Number of releases to include in the matrix'
    required: true
    default: "3"
  release_url:
    description: 'URL to Alpine releases JSON'
    required: false
    default: "https://www.alpinelinux.org/releases.json"

outputs:
  os:
    description: 'List of OS names'
    value: ${{ steps.alpine.outputs.os }}
  version:
    description: 'List of Alpine versions'
    value: ${{ steps.alpine.outputs.version }}
  matrix:
    description: 'Matrix of Alpine versions'
    value: ${{ steps.alpine.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - id: alpine
      shell: bash
      run: ${{ github.action_path }}/action.sh ${{ inputs.release_url }} ${{ inputs.count }}
