name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: alpine
        uses: ./
    outputs:
      alpine: ${{ steps.alpine.outputs.matrix }}

  build:
    runs-on: ubuntu-latest
    needs: generate
    strategy:
      matrix: ${{ fromJson(needs.generate.outputs.alpine) }}
    steps:
      - run: echo "Build ${{ matrix.version}}"
