name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: alpine
        uses: ./
    outputs:
      alpine: ${{ steps.alpine.outputs }}

  build:
    runs-on: ubuntu-latest
    needs: generate
    strategy:
      matrix: ${{ needs.generate.outputs.alpine.matrix }}
    steps:
      - run: echo "Build ${{ matrix.os }} ${{ matrix.version }}"
